//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CastInfo
    {
        public int MovieID { get; set; }
        public string ActorName { get; set; }
        public int ActorID { get; set; }
    
        public virtual Celebrity Celebrity { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
